/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odiseaespacial.system;

import java.awt.Color;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author bruno
 */
public class VentanaJuego_201709362 extends javax.swing.JFrame{
    private MovimientoNave_201709362 movimientoNave = new MovimientoNave_201709362();
    private int alto = 480;
    private int ancho = 1100;
    /**
     * Creates new form VentanaJuego_201709362
     */
    public VentanaJuego_201709362() {
        initComponents();
        
        setSize(ancho, alto);
        setResizable(false);
        getContentPane().setLayout(null);
        
        lblEspacio = new JLabel();
        getContentPane().add(lblEspacio);
        lblEspacio.setBounds(10,90,1070,340);
        lblEspacio.setBackground(Color.yellow);
        lblEspacio.setOpaque(true);
        
        
        
        Aplicacion_201709362.lblNave = new JLabel("hola");
        Aplicacion_201709362.lblNave.setBackground(Color.BLACK);
        Aplicacion_201709362.lblNave.setOpaque(true);
        Aplicacion_201709362.lblNave.setBounds(0,535,55,85);
        lblEspacio.add(Aplicacion_201709362.lblNave);
        
        //uso otro distinto al generado, para aqregar variables estaticas
        //iniciarComponentes();
        /*this.addKeyListener((KeyListener)movimientoNave);
        Movimie*/
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel25.setText("jLabel25");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(447, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaJuego_201709362.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaJuego_201709362.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaJuego_201709362.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaJuego_201709362.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaJuego_201709362().setVisible(true);
//            }
//        });
//    }
    
    private class ManejoDeTeclas implements KeyListener{
        //movimiento nave----0 arriba-1 abajo
        @Override
        public void keyPressed(KeyEvent ke) {
            switch(ke.getKeyCode()){
                case KeyEvent.VK_UP:
                    System.out.println("arriba");
                    Aplicacion_201709362.movimientoNave = 0;
                    movimientoNave.start();
                    break;
                case KeyEvent.VK_DOWN:
                    Aplicacion_201709362.movimientoNave = 1;
                    System.out.println("abajo");
                    break;
            }
        }

        @Override
        public void keyTyped(KeyEvent ke) {}

        @Override
        public void keyReleased(KeyEvent ke) {
            //terminar hilo
            movimientoNave.interrupt();
            Aplicacion_201709362.movimientoNave = 2;
        }
    }
    
    private class MovimientoNave_201709362 extends Thread{
    
    @Override
    public void run() {
        Timer timer = new Timer(5, (ae) -> {
            int y = Aplicacion_201709362.lblNave.getY();
            int x;
            Rectangle bounds;
            switch(Aplicacion_201709362.movimientoNave){
                // 0 arriba - 1 abajo
                case 0:
                    y = y+2;
                    bounds = Aplicacion_201709362.lblNave.getBounds();
                    x = (int)bounds.getX();
                    bounds.translate(x, y);
                    Aplicacion_201709362.lblNave.setBounds(bounds);
                    break;
                case 1:
                    y = y-2;
                    bounds = Aplicacion_201709362.lblNave.getBounds();
                    x = (int)bounds.getX();
                    bounds.translate(x, y);
                    Aplicacion_201709362.lblNave.setBounds(bounds);
                    break;
            }
            Aplicacion_201709362.panelJuego.repaint();
        });
        timer.start();
    }
}
    private javax.swing.JLabel lblEspacio;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
