/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odiseaespacial.system;

import javax.swing.JFrame;
import odiseaespacial.bean.Configuracion_201709362;

/**
 *
 * @author TrexT
 */
public class VentanaConfiguracion_201709362 extends javax.swing.JFrame {
    private Configuracion_201709362 configuracion;
    /**
     * Creates new form Configuracion_201709362
     * @param ventanaPrincipal
     */
    public VentanaConfiguracion_201709362(JFrame ventanaPrincipal) {
        initComponents();
        //cargar configuracion
        cargarConfiguracion();
    }
    
    private void cargarConfiguracion(){
        Configuracion_201709362 config = Aplicacion_201709362.configuracion;
        radioButtonAumentoTiempo.setSelected(config.isAumentoTiempo());
        radioButtonPuntosExtra.setSelected(config.isPuntosExtra());
        radioButtonAumentoVelocidad.setSelected(config.isAumentoVelocidad());
        radioButtonDisminucionTiempo.setSelected(config.isDisminucionTiempo());
        radioButtonPenalizacion.setSelected(config.isPenalizacion());
        radioButtonCongelacion.setSelected(config.isCongelacion());
        
        switch(config.getFrecuenciaItems()){
            case 5000:
                //normal
                comboBoxFrecuenciaItems.setSelectedIndex(0);
                break;
            case 3000:
                //alta
                comboBoxFrecuenciaItems.setSelectedIndex(1);
                break;
            case 7500:
                //baja
                comboBoxFrecuenciaItems.setSelectedIndex(2);
                break;
        }
        
        switch(config.getNivelVelocidad()){
            case 750:
                //normal
                comboBoxNivelVelocidad.setSelectedIndex(0);
                break;
            case 100:
                //alta
                comboBoxNivelVelocidad.setSelectedIndex(1);
                break;
            case 2000:
                //baja
                comboBoxNivelVelocidad.setSelectedIndex(2);
                break;
        }
        
        switch(config.getDuracionPartida()){
            case 90:
                //90s
                comboBoxDuracion.setSelectedIndex(0);
                break;
            case 120:
                //120s
                comboBoxDuracion.setSelectedIndex(1);
                break;
            case 180:
                //180s
                comboBoxDuracion.setSelectedIndex(2);
                break;
            case 240:
                //240s
                comboBoxDuracion.setSelectedIndex(3);
                break;
            case 300:
                //300s
                comboBoxDuracion.setSelectedIndex(4);
                break;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radioButtonAumentoTiempo = new javax.swing.JRadioButton();
        radioButtonPuntosExtra = new javax.swing.JRadioButton();
        radioButtonDisminucionTiempo = new javax.swing.JRadioButton();
        radioButtonPenalizacion = new javax.swing.JRadioButton();
        radioButtonCongelacion = new javax.swing.JRadioButton();
        radioButtonAumentoVelocidad = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        comboBoxFrecuenciaItems = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboBoxNivelVelocidad = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        comboBoxDuracion = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("ITEMS");

        jLabel2.setText("Aumento de tiempo");

        jLabel3.setText("Puntos extra");

        jLabel4.setText("Aumento de velocidad");

        jLabel5.setText("Disminuciòn de tiempo");

        jLabel6.setText("Penalizacion");

        jLabel7.setText("Congelaciòn");

        radioButtonAumentoTiempo.setSelected(true);

        radioButtonPuntosExtra.setSelected(true);

        radioButtonDisminucionTiempo.setSelected(true);

        radioButtonPenalizacion.setSelected(true);

        radioButtonCongelacion.setSelected(true);

        radioButtonAumentoVelocidad.setSelected(true);

        jLabel8.setText("Frecuencia");

        comboBoxFrecuenciaItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Alta", "Baja" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioButtonCongelacion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioButtonPenalizacion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioButtonDisminucionTiempo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(radioButtonAumentoVelocidad))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioButtonAumentoTiempo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioButtonPuntosExtra)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxFrecuenciaItems, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonAumentoTiempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonPuntosExtra))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radioButtonDisminucionTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(radioButtonPenalizacion, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radioButtonCongelacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(comboBoxFrecuenciaItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(radioButtonAumentoVelocidad))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("VELOCIDAD");

        jLabel10.setText("Nivel");

        comboBoxNivelVelocidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nomal", "Alto", "Bajo" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboBoxNivelVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboBoxNivelVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("DURACION");

        comboBoxDuracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "90s", "120s", "180s", "240s", "300s" }));

        jLabel12.setText("Tiempo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(comboBoxDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        Aplicacion_201709362.ventanaPrincipal.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //agregar propiedades al objeto configuracion
        configuracion = new Configuracion_201709362();
        //configuracion de items
        configuracionItems();
        //configuracion de velocidad
        configuracionVelocidad();
        //configuracion de duracion de partida
        configuracionTiempoPartida();
        //enviar configuracion
        Aplicacion_201709362.configuracion = configuracion;
        this.setVisible(false);
        Aplicacion_201709362.ventanaPrincipal.setVisible(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void configuracionItems(){
        configuracion.setAumentoTiempo(radioButtonAumentoTiempo.isSelected());
        configuracion.setPuntosExtra(radioButtonPuntosExtra.isSelected());
        configuracion.setAumentoVelocidad(radioButtonAumentoVelocidad.isSelected());
        configuracion.setDisminucionTiempo(radioButtonDisminucionTiempo.isSelected());
        configuracion.setPenalizacion(radioButtonPenalizacion.isSelected());
        configuracion.setCongelacion(radioButtonCongelacion.isSelected());
        configuracion.setContadorItems(0);
        if (configuracion.isAumentoTiempo() || configuracion.isPuntosExtra()|| configuracion.isAumentoVelocidad()|| configuracion.isDisminucionTiempo()|| configuracion.isPenalizacion()|| configuracion.isCongelacion()) {
            configuracion.setContadorItems(1);
        }
        
        switch(comboBoxFrecuenciaItems.getSelectedIndex()){
            case 0:
                //normal
                configuracion.setFrecuenciaItems(5000);
                break;
            case 1:
                //alta
                configuracion.setFrecuenciaItems(3000);
                break;
            case 2:
                //baja
                configuracion.setFrecuenciaItems(7500);
                break;
        }
    }
    
    private void configuracionVelocidad(){
        switch(comboBoxNivelVelocidad.getSelectedIndex()){
            case 0:
                //normal
                configuracion.setNivelVelocidad(750);
                break;
            case 1:
                //alta
                configuracion.setNivelVelocidad(100);
                break;
            case 2:
                //baja
                configuracion.setNivelVelocidad(2000);
                break;
        }
    }
    
    private void configuracionTiempoPartida(){
        switch(comboBoxDuracion.getSelectedIndex()){
            case 0:
                //90s
                configuracion.setDuracionPartida(90);
                break;
            case 1:
                //120s
                configuracion.setDuracionPartida(120);
                break;
            case 2:
                //180s
                configuracion.setDuracionPartida(180);
                break;
            case 3:
                //240s
                configuracion.setDuracionPartida(240);
                break;
            case 24:
                //300s
                configuracion.setDuracionPartida(300);
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboBoxDuracion;
    private javax.swing.JComboBox<String> comboBoxFrecuenciaItems;
    private javax.swing.JComboBox<String> comboBoxNivelVelocidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton radioButtonAumentoTiempo;
    private javax.swing.JRadioButton radioButtonAumentoVelocidad;
    private javax.swing.JRadioButton radioButtonCongelacion;
    private javax.swing.JRadioButton radioButtonDisminucionTiempo;
    private javax.swing.JRadioButton radioButtonPenalizacion;
    private javax.swing.JRadioButton radioButtonPuntosExtra;
    // End of variables declaration//GEN-END:variables
}
